apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: monitoring

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus/configmap.yaml
  - prometheus/rules/alert-rules.yaml
  - prometheus/deployment.yaml
  - loki/configmap.yaml
  - loki/deployment.yaml
  - grafana/configmap.yaml
  - grafana/dashboards-configmap.yaml
  - grafana/deployment.yaml
  - alertmanager/configmap.yaml
  - alertmanager/deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: monitoring
  app.kubernetes.io/managed-by: kustomize
