apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: bmi-health-tracker
type: Opaque
data:
  username: Ym1pX3VzZXI= # bmi_user
  password: c3Ryb25ncGFzc3dvcmQ= # strongpassword
  database: Ym1pZGI= # bmidb
  db-url: cG9zdGdyZXNxbDovL2JtaV91c2VyOnN0cm9uZ3Bhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZTo1NDMyL2JtaWRi
